# Generated by Django 2.2.2 on 2019-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_number', models.IntegerField()),
                ('scheduled_datetime', models.DateTimeField()),
                ('expected_arrival_datetime', models.DateTimeField()),
                ('departure', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('fare', models.IntegerField()),
                ('flight_duration', models.TimeField()),
            ],
        ),
    ]
